# Generated by Django 4.1 on 2023-07-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 7, 3, 10, 56, 16, 361980))),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
