# Generated by Django 4.1 on 2023-07-03 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 10, 59, 4, 959361)),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='books'),
        ),
    ]
