# Generated by Django 4.1 on 2023-09-03 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 15, 46, 58, 902206)),
        ),
    ]
