# Generated by Django 4.2.1 on 2023-06-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='dept',
        ),
        migrations.AddField(
            model_name='courses',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculties.faculties'),
        ),
        migrations.AddField(
            model_name='dept',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculties.faculties'),
        ),
    ]
