# Generated by Django 4.2.1 on 2023-06-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculties', '0003_alter_courses_options_alter_dept_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='my_courses', to='Faculties.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculties.dept')),
            ],
        ),
    ]
