# Generated by Django 4.2.1 on 2023-06-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='c',
        ),
    ]
