# Generated by Django 4.1 on 2023-07-02 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Faculties", "0004_department_courses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("examination", "0002_remove_objectives_c"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsTrials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveBigIntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 2, 23, 23, 0, 546172)
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Faculties.courses",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
