# Generated by Django 4.1 on 2023-08-04 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_studentstrials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstrials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 14, 52, 11, 920725)),
        ),
    ]
