# Generated by Django 4.1 on 2023-09-03 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_alter_studentstrials_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstrials',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 15, 46, 58, 881466)),
        ),
    ]
