# Generated by Django 4.2.1 on 2023-06-13 06:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuestion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000000000000, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=100)),
                ('post', tinymce.models.HTMLField()),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='user_blog.postquestion')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
