# Generated by Django 4.1 on 2023-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostedExam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedexam',
            name='id',
            field=models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
